name: Linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: ${{ matrix.os.name }} ( ${{matrix.os.compiler }}, ${{ matrix.mode }} )
    runs-on: ${{ matrix.os.value }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - {
           name: "Ubuntu",
           compiler: "GCC",
           value: ubuntu-22.04,
           triplet: "x64-linux"
        }
            
        mode: [release, debug, asan]
    steps:
        - name: Install apt deps
          id: aptdeps
          run: |
            sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
            sudo add-apt-repository -y ppa:deadsnakes/ppa
            sudo apt -q update
            sudo apt -y install \
              gcc \
              g++ \
              tar \
              curl \
              zip \
              unzip \
              cmake \
              meson \
              ninja-build

        - name: Install xmake
          uses: xmake-io/github-action-setup-xmake@v1

        - name: Checkout
          uses: actions/checkout@v2
          with:
            fetch-depth: 0
            
        - name: Configure & Build
          id: confandbuild
          run: |
            xmake f -v --yes -m ${{ matrix.mode }}
            xmake b -v

        - name: Install
          id: install
          run: |
            xmake install -v --installdir="${{ runner.workspace }}/Module2Header_Output"

        - name: Upload artifacts
          id: upload
          uses: actions/upload-artifact@v1
          with:
            name: ${{ matrix.os.name }}-${{ matrix.os.compiler }}-${{ matrix.mode }}
            path: ${{ runner.workspace }}/Module2Header_Output
 